spring:
  profiles:
    active: PROD
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/term
    username: postgres
    password: KhPoDwQL%0UX1
  jms:
    listener:
      receive-timeout: 60000
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate: dialect:org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:/db/migration/
    validate-on-migrate: true
    baseline-on-migrate: true
    out-of-order: true
server:
  error:
    include-message: always
  port: 8082
logging:
  config: classpath:log4j2.xml
  file:
    path: /logs/
    max-size: 10MB
